version: '3.8'

services:
  wallet-tracker-bot:
    build: .
    container_name: wallet-tracker-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - BSCSCAN_API_KEY=${BSCSCAN_API_KEY}
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
